# Generated by Django 4.2.24 on 2025-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_fetured',
            new_name='is_featured',
        ),
    ]
